export type AssetType = "character" | "scene" | "prop" | "style" | "other";
export type AssetMediaKind = "image" | "video" | "none";
export type AssetImageModel = "gpt-image-2" | "seedream-4" | "seedream-4-5";

export type ShotStatus = "draft" | "scripted" | "generating" | "ready" | "error" | "cancelled";
export type SeedanceVariant = "fast" | "standard";

export interface StoryCharacter {
  name: string;
  role: string;
  arc: string;
  assetId?: string;
  assetMention?: string;
}

export interface StoryBeat {
  index: number;
  title: string;
  purpose: string;
  plot: string;
  emotion: string;
  visual: string;
  assetMentions: string[];
  durationSec: number;
}

export interface StoryPlan {
  premise: string;
  synopsis: string;
  theme: string;
  tone: string;
  characters: StoryCharacter[];
  beats: StoryBeat[];
  locked: boolean;
  updatedAt?: string;
  model?: string;
}

export interface Asset {
  id: string;
  name: string;
  type: AssetType;
  mediaKind: AssetMediaKind;
  description: string;
  prompt: string;
  mediaUrl?: string;
  imageUrl?: string;
  referenceImageUrl?: string;
  tosObjectKey?: string;
  tosPublishedAt?: string;
  tags: string[];
  /**
   * Optional parent asset id. When set, image generation will pass the parent's reference image as
   * a conditioning input to the generator, so derived variants (e.g. younger / older / different
   * outfit versions of the same character) keep the parent's facial identity.
   */
  parentAssetId?: string;
  /**
   * Optional owning shot id. When set, this asset is a private "shot-scoped sketch" that:
   *   - is NOT shown in the global Asset Library UI
   *   - is NOT picked up by other shots' @mention scanning
   *   - is automatically deleted when the owning shot (or its session) is deleted
   * Typical usage: per-shot storyboard sketches generated by Seedream that act as reference_image
   * input to the Seedance video generator for that one shot only.
   */
  ownerShotId?: string;
  /**
   * Optional owning session id. When set, this asset is "session-scoped":
   *   - it IS visible in the Asset Library UI, but only while that session is open
   *   - other sessions' shots cannot @mention it
   *   - it is cascade-deleted when the owning session is deleted
   *   - it can be promoted to a global asset (POST /api/assets/:id/promote), which clears this
   *     field — afterwards it behaves like any other global asset and survives session deletion.
   * If both ownerShotId and ownerSessionId are set, ownerShotId wins (it's the more specific
   * private-sketch scope) and ownerSessionId is informational.
   */
  ownerSessionId?: string;
  updatedAt: string;
  createdAt: string;
}

export interface Shot {
  id: string;
  sessionId: string;
  index: number;
  title: string;
  script: string;
  camera: string;
  durationSec: number;
  storyBeatIndex?: number;
  assetIds: string[];
  rawPrompt?: string;
  prompt: string;
  debugNote?: string;
  seedanceVariant?: SeedanceVariant;
  usePreviousShotClip?: boolean;
  previousShotClipSec?: number;
  previousShotClipSecOverride?: boolean;
  referenceClipUrl?: string | null;
  referenceAudioUrl?: string | null;
  referenceClipPreviewUrl?: string | null;
  referenceAudioPreviewUrl?: string | null;
  /**
   * Optional asset id that should be used as the first frame of this shot. When set, the shot enters
   * Seedance "first-frame" mode and reference_image / reference_video / reference_audio are dropped
   * from the payload (per BytePlus ModelArk docs - first/last frame mode cannot be combined with
   * other reference media). Primarily intended for shot 1 of a session, but allowed on any shot;
   * when present it takes precedence over `usePreviousShotClip`.
   */
  firstFrameAssetId?: string;
  videoUrl?: string;
  renders?: ShotRender[];
  generationTaskId?: string | null;
  generationModel?: string;
  generationStartedAt?: string | null;
  status: ShotStatus;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}

export interface ShotRender {
  id: string;
  model: string;
  prompt: string;
  status?: ShotStatus;
  title?: string;
  durationSec?: number;
  seedanceVariant?: SeedanceVariant;
  assetIds?: string[];
  rawPrompt?: string;
  usePreviousShotClip?: boolean;
  previousShotClipSec?: number;
  previousShotClipSecOverride?: boolean;
  referenceClipUrl?: string;
  referenceAudioUrl?: string;
  referenceClipPreviewUrl?: string;
  referenceAudioPreviewUrl?: string;
  /** Snapshot of `Shot.firstFrameAssetId` at the time the render was submitted. */
  firstFrameAssetId?: string;
  videoUrl?: string;
  remoteVideoUrl?: string;
  generationTaskId?: string | null;
  generationStartedAt?: string | null;
  error?: string | null;
  note?: string;
  createdAt: string;
}

export type StitchStatus = "idle" | "running" | "ready" | "error";

export type NarrationStatus = "idle" | "running" | "ready" | "error";
export type NarrationStrategy = "natural";

export interface Session {
  id: string;
  title: string;
  logline: string;
  style: string;
  targetDurationSec: number;
  story?: StoryPlan;
  finalVideoUrl?: string;
  finalVideoSignature?: string;
  /**
   * Stitch task lifecycle. `running` means a background worker is currently materializing the
   * inputs and running ffmpeg concat for this session. `ready` means `finalVideoUrl` is fresh and
   * matches the latest `finalVideoSignature`. `error` means the last run failed (see
   * `stitchError`); a subsequent /stitch call will retry. `idle` (or undefined) means no stitch
   * has been attempted, or the session is back to a clean slate.
   *
   * The HTTP route never blocks on stitch progress – it always returns immediately with the
   * current snapshot. Clients poll `POST /api/sessions/:id/stitch/poll` (or just `GET /api/state`)
   * to observe completion. This decouples long-running ffmpeg work from any single client
   * connection, so a dropped fetch / browser refresh / agent timeout cannot interrupt or partially
   * cancel the underlying work.
   */
  stitchStatus?: StitchStatus;
  /** ISO time the current running stitch job started. */
  stitchStartedAt?: string;
  /** ISO time the most recent stitch status update happened (ready/error transition). */
  stitchUpdatedAt?: string;
  /** Human-readable last error from the most recent failed stitch attempt. */
  stitchError?: string;
  /** Human-readable current phase, e.g. "downloading shot 4/5", "ffmpeg concat", "writing final". */
  stitchProgress?: string;
  /** Signature of the inputs of the currently running stitch job; used for singleflight. */
  stitchRunningSignature?: string;

  /**
   * Auto narration + subtitle pipeline. Runs *after* a successful stitch and writes a second
   * mp4 (subtitles hardcoded into the picture) plus a sidecar .srt. Mirrors the stitch lifecycle:
   *   - `running`: background ffmpeg+TTS worker is processing
   *   - `ready`: `narrationVideoUrl` / `narrationSubtitleUrl` are fresh against the current
   *     `finalVideoSignature` (compare with `narrationSignature` to detect staleness when stitch
   *     was redone afterwards)
   *   - `error`: see `narrationError`
   *
   * `narrationSignature` is `sha1(script + voice + strategy + finalVideoSignature)` so that the
   * UI can grey out the download buttons when stitch was rebuilt after the narration was made.
   */
  narrationScript?: string;
  narrationVoice?: string;
  narrationStrategy?: NarrationStrategy;
  narrationStatus?: NarrationStatus;
  narrationStartedAt?: string;
  narrationUpdatedAt?: string;
  narrationError?: string;
  narrationProgress?: string;
  narrationVideoUrl?: string;
  narrationSubtitleUrl?: string;
  narrationSignature?: string;
  narrationRunningSignature?: string;
  /**
   * The `finalVideoSignature` value that was active when this narration was built. The UI
   * compares it against the current `finalVideoSignature` to detect a stale narration after a
   * re-stitch and grey out the "下载" buttons with a "请重新生成解说" hint.
   */
  narrationBuiltForFinalVideoSignature?: string;

  updatedAt: string;
  createdAt: string;
}

export interface StoreSnapshot {
  assets: Asset[];
  sessions: Session[];
  shots: Shot[];
}

export interface SessionWithShots extends Session {
  shots: Shot[];
}

export interface CreateSessionPayload {
  title?: string;
  logline?: string;
  style?: string;
  targetDurationSec?: number;
  shotCount?: number;
}

export interface GenerateAssetPayload {
  assetId: string;
  model?: AssetImageModel;
}

export interface ExpandAssetPromptPayload {
  asset: Partial<Asset>;
}

export interface ExpandAssetPromptResult {
  prompt: string;
  model: string;
}

export interface GenerateShotPayload {
  shotId: string;
}
